title: <p align="center"> Imran Khan </p>
logo: /assets/img/Imran_Khan.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/imran-khan-b991b31b/">LinkedIn</a> |
  <a href="https://github.com/ikscorpio">GitHub</a>
  
  <br>   
  I Am A Telecommunication Engineer Having 13 Years OF Working Experience.
  I Have Worked With Leading Companies Like Ericsson, Aircel, Nokia, Adacelworks And GTL Limited etc. 
  <br>
  </p>



theme: jekyll-theme-minimal
